### ISSUE TITLE
Automatic screen name includes object address and makes it unusable

### ISSUE THREAD

**Issue by nezhyborets** [amplitude/Amplitude-Swift#100]
## Current Behavior

Currently screen name is captured in a way that includes object address, which is different each time object instantiated. This way I can't filter by actual Screen Name because there are plenty of records for single screen name.
<img width="453" alt="Screenshot 2023-11-23 at 16 36 12" src="https://github.com/amplitude/Amplitude-Swift/assets/2803931/a8cfdeb1-36ac-4fd4-96cd-9ecdc6f0c9c1">

## Possible Solution

There are plenty of possible solutions, but the easiest one would be to just print Class of an object, and not include brackets, object address etc. So that it would be:
`FriendProfile` instead of `<Evenly.FriendProfile: 0x10501e800>`

## Steps to Reproduce
 

1. Just enable `defaultTracking` so that screenViews are tracked, so `defaultTracking: .init(screenViews: true)` or `defaultTracking: .ALL` and see what's received by Amplitude

## Environment
- SDK Version:  Amplitude-Swift 1.1.0
- OS Info:  iOS 17.0.1, iOS Simulator iPhone 15 Pro Max

**Comment by crleona** [comment]
Hi @nezhyborets - this should be fixed in the latest release.
