### ISSUE TITLE
Events are sent in wrong order or missed?

### ISSUE THREAD

**Issue by emartinson** [amplitude/Amplitude-Swift#102]
## Summary

Hi! I've been using Amplitude for years and after migrating from `Amplitude-iOS` to `Amplitude-Swift` library I see some strange thing in User Events Stream:
As I see some events are in wrong order (Session End is before Session Start). Some days there is only one event (which is impossible without Start Session & End Session).
Do you have any clue what might be the reason?

<img width="648" alt="image" src="https://github.com/amplitude/Amplitude-Swift/assets/10173008/3439f7a6-1dee-40f1-a34d-96902a0dca52">

This screenshot was taken from user stream from Unique chart:

<img width="1038" alt="image" src="https://github.com/amplitude/Amplitude-Swift/assets/10173008/cee44186-4c54-46a0-a048-1de013e08106">

May this issue correlate with denied iOS 14 App Tracking Alert?
----
AmplitudeSwift (0.7.3)
AnalyticsConnector (1.0.3)

**Comment by emartinson** [comment]
Thank you for your reply!
Org ID: 139422

We've updated to 1.1.0 and will check it out after release. I'll inform you asap

**Comment by liuyang1520** [comment]
Hi @emartinson , thanks for reporting this!

I have randomly viewed the data in your org, the data are looking good to me, and I saw you have already updated to the newer version SDK 👍.

> As I see some events are in wrong order (Session End is before Session Start). Some days there is only one event (which is impossible without Start Session & End Session)

Session End event can be before the Session Start event, as this Session End is for the last session. You can double check the `session_id` in the event stream, newer sessions should have larger value.

Same reason, you might see a Session Start event without a Session End temporarily, as the Session End is not sent at that time yet (e.g., if the app is killed manually), but it should get sent before the next session.

Thanks!

**Comment by emartinson** [comment]
Sorry, we had a race condition while configuring SDK and some events were randomly sending to different environments.
