### ISSUE TITLE
Tweak code generation

### ISSUE THREAD

**Issue by masterchiip** [amplitude/Amplitude-Swift#106]
## Summary

When we generate the code with ampli-cli we're getting some enum cases having reserved keywords names.
Now we need to escape them manually to be able to build.
There's a way to tweak the generation of the code to avoid it?

![image](https://github.com/amplitude/Amplitude-Swift/assets/4965209/9f112063-ed71-43c7-9cd5-be6e87eeb18d)

**Comment by crleona** [comment]
Hi @masterchiip, please open issues for Ampli on the https://github.com/amplitude/ampli-examples repo so they can be directed to the right place. Thanks!
