### ISSUE TITLE
disableIDFV on tracking options has no effect

### ISSUE THREAD

**Issue by alessiolapenna** [amplitude/Amplitude-Swift#107]
Trying to dissable IDFV tracking, has no effect, since the Amplitude initializer set its deviceid as the idfv before the tracking options are even checked.
Initializing the sdk like this:
```
Amplitude(
            configuration: Configuration(
                apiKey: Constants.ExternalSDKs.Amplitude.apiKey(),
                trackingOptions: TrackingOptions()
                    .disableTrackIpAddress()
                    .disableTrackIDFV()
            )
        )
```
in the Amplitude initializer the ContextPlugin is initialized:
```
func initializeDeviceId() {
        var deviceId = amplitude?.state.deviceId
        if isValidDeviceId(deviceId) {
            return
        }
        if deviceId == nil {
            deviceId = staticContext["idfv"] as? String
        }
        if deviceId == nil {
            deviceId = NSUUID().uuidString
        }
        _ = amplitude?.setDeviceId(deviceId: deviceId)
    }
```
this will set the deviceId on the amplitude instance as the idfv.
Then later even if the event.idfv field will not be filled, the device id will still be equal to the idfv.

## Expected Behavior
disabling the idfv tracking should also anonymize the deviceid on the amplitude instance

## Current Behavior
amplitude instance device id is still equal to the idfv

## Possible Solution
When the ConectPlugin is initialized, the tracking options should be passed down, and when the deviceid is initialized a check should be done, and if idfv is disabled, the device id should be set to a random uuid

## Steps to Reproduce
1. init the sdk with this code:
```
Amplitude(
            configuration: Configuration(
                apiKey: Constants.ExternalSDKs.Amplitude.apiKey(),
                trackingOptions: TrackingOptions()
                    .disableTrackIpAddress()
                    .disableTrackIDFV()
            )
        )
```
2. track any event
3. the event.deviceid is equal to idfv

## Environment
- SDK Version: 1.1.0
- OS Info: any iOS

**Comment by crleona** [comment]
Hi @alessiolapenna - this should be fixed in the latest release.
