### ISSUE TITLE
Potential issue with cache file location

### ISSUE THREAD

**Issue by theolampert** [amplitude/Amplitude-Swift#112]
While evaluating the `Amplitude-Swift` at work, we've had issues with other project's (unrelated to us) events showing up in our dashboard, we have screenshots demonstrating this, but I don't want to post them here, please let me know if you need to see these.

What it looks like is as if all Mac apps running on a user's machine, with multiple instances of the Amplitude Swift SDK will write their events to the same cache file, which leads to leaking events into other people's dashboards when these are batched. This is tricky to reproduce because it has to happen within a fairly short time window before the events are batched. Because our app is a menu bar app that interacts with other apps, it opens up the possibility of this happening much more frequently.

## Expected Behavior
The cache files/folders should be unique per instance.

## Current Behavior
All instances of the SDK share a single cache file.

## Possible Solution
Create unique cache folders/files per instance.

## Steps to Reproduce
Create two separate Amplitude instances with separate API keys and run them at the same time, observe that they both write to the same location, run a debugging proxy or similar to inspect outgoing requests. You'll have to simulate some situation in which both write to the same file within the timeout that batches these requests.

## Environment
- SDK Version: 1.1.0
- OS Info: N/A

Please let me know if I'm missing something here.

**Comment by izaaz** [comment]
@theolampert can you please send an email with the details to sdk.dev@amplitude.com?

**Comment by jpeinelt** [comment]
Sounds very similar to https://github.com/amplitude/Amplitude-iOS/issues/349

**Comment by theolampert** [comment]
> Sounds very similar to https://github.com/amplitude/Amplitude-iOS/issues/349

Yes this looks very similar to what I found. The original author also suggests two possible solutions.

@izaaz I'll email through some more details shortly, please be aware this also been reported by our PO through the normal support channels.

**Comment by justin-fiedler** [comment]
Hi @theolampert fix was released `v1.2.0`.

https://github.com/amplitude/Amplitude-Swift/releases/tag/v1.2.0
