### ISSUE TITLE
setOnce operation does not work

### ISSUE THREAD

**Issue by dams229** [amplitude/Amplitude-Swift#115]
Calling `setOnce(property: String, value: Float)` on Identify does not set the value properly

## Expected Behavior
Value of `property` should be set only once

## Current Behavior
A property name `$set_once.PROPERTY_NAME` is set

## Possible Solution
Change `SET_ONCE` operation name in code

## Steps to Reproduce
Call `Identify.setOnce(...)`

## Environment
- SDK Version: 1.3.0
- OS Info: Any iOS

**Comment by qingzhuozhen** [comment]
Thanks for submitting the issue and add a fix. The fix is now included in v1.3.3, feel free to upgrade and let us know if that help resolve the issue or not.

**Comment by dams229** [comment]
Perfect, it works!
