### ISSUE TITLE
Automatic screen tracking doesn't work

### ISSUE THREAD

**Issue by fvolchyok** [amplitude/Amplitude-Swift#121]
## Expected Behavior
Using `defaultTracking.screenViews = true` or `DefaultTrackingOptions.ALL` on Amplitude initialisation should enable automatic screen tracking

## Current Behavior
Screen events don't track automatically.

Debugging shows that `UIViewController.viewDidAppear` swizzled successfully, but tracking fails on bundle check:

https://github.com/amplitude/Amplitude-Swift/blob/0b77c2e123f8e47531ea62d2d31da105c74d7391/Sources/Amplitude/Plugins/iOS/UIKitScreenViews.swift#L55-L58

where
```
(lldb) po bundle.bundlePath
"/System/Library/PrivateFrameworks/UIKitCore.framework"

(lldb) po Bundle.main.bundlePath
"/private/var/containers/Bundle/Application/4AC5FC00-2EE0-446D-AB8F-190B8B030758/myapp.app"
```

For context which might be related: my UIViewControllers are in a separate framework, not in the main bundle, but either way it must not interfere with tracking. 

If I understand correctly, and as lldb printing above suggests - tracking can't happen because  in my case`Bundle.main.bundlePath` obviously can't be a prefix for `bundle.bundlePath`.

## Possible Solution
Revise bundle checks. I wonder what could have been the reason to put this check in the first place?

## Steps to Reproduce
1. Create a ViewController, potentially in a framework (referenced by main app target).
2. Check if screen events are being tracked.

## Environment
- SDK Version: Amplitude-Swift 1.1.0
- iOS version: 15.7.3
- Xcode: 15.1
- OS Info: MacOS 14.3.1 (23D60)

**Comment by fvolchyok** [comment]
My bad, I misdiagnosed the issue, further investigation required on my part

**Comment by crleona** [comment]
Hi @fvolchyok - this should be fixed in the latest release.
