### ISSUE TITLE
visionOS support

### ISSUE THREAD

**Issue by aureliendelrue** [amplitude/Amplitude-Swift#130]
In my application (iOS/macOS/watchOS/visionOS), your SDK is working for visionOS but your web console did not support it (no device type, device OS, etc...), currently the only way to filter visionOS events is by the application version. Any plan to support it ?

**Comment by izaaz** [comment]
@aureliendelrue - Thanks for raising this issue. This is currently in our backlog but we don't have an ETA for this yet. Can you please share a link to the event that you sent from vision os but the device type info was not properly populated?

**Comment by aureliendelrue** [comment]
For example : https://app.amplitude.com/analytics/mswidgets/project/581398/search/amplitude_id%3D843804508303

**Comment by izaaz** [comment]
Thank you @aureliendelrue. I'll add this as an example for when this gets prioritized.

**Comment by drewolbrich** [comment]
@izaaz Thank you for working to add visionOS support. 😀

**Comment by drewolbrich** [comment]
@aureliendelrue Until Amplitude-Swift supports visionOS, I've discovered that as a workaround, if your app's analytics happens to be funneled through a single call to `Amplitude/track(eventType:properties:options:)`, it appears you can use code like the following to manually specify the visionOS device and platform yourself:
```
#if os(visionOS)
    // As of March 2024, Amplitude-Swift doesn't report the visionOS platform or OS version,
    // so we do it ourselves. We can remove this once the Amplitude-Swift SDK supports visionOS.
    // See https://github.com/amplitude/Amplitude-Swift/issues/130
    private let manuallyReportVendorSystem = true
#else
    private let manuallyReportVendorSystem = false
#endif
    
    lazy var amplitude: Amplitude = {
        let configuration = Configuration(apiKey: AppConfiguration.amplitudeAPIKey)

        if manuallyReportVendorSystem {
            // We'll report these ourselves in `trackEvent(_:withEventProperties:)`.
            configuration.trackingOptions.disableTrackDeviceManufacturer()
            configuration.trackingOptions.disableTrackDeviceModel()
            configuration.trackingOptions.disableTrackIDFV()
            configuration.trackingOptions.disableTrackPlatform()
            configuration.trackingOptions.disableTrackOsName()
            configuration.trackingOptions.disableTrackOsVersion()
        }

        let amplitude = Amplitude(configuration: configuration)
        return amplitude
    }()
    
    func trackEvent(_ eventType: String, withEventProperties eventProperties: [String: Any] = [:]) {
        let eventOptions = EventOptions()
        
        if manuallyReportVendorSystem {
            eventOptions.deviceManufacturer = "Apple"
#if targetEnvironment(simulator)
            // This is consistent with the Amplitude Swift SDK, which doesn't recognize the
            // simulator when running on Apple Silicon.
            eventOptions.deviceModel = ""
#else
            eventOptions.deviceModel = UIDevice.current.name
#endif
            eventOptions.idfa = UIDevice.current.identifierForVendor?.uuidString
            eventOptions.platform = UIDevice.current.systemName
            // This matches the behavior of the Amplitude Swift SDK.
            eventOptions.osName = UIDevice.current.systemName.lowercased()
            eventOptions.osVersion = UIDevice.current.systemVersion
        }

        amplitude.track(eventType: eventType, eventProperties: eventProperties, options: eventOptions)
    }
```

**Comment by izaaz** [comment]
Thanks for the work around @drewolbrich. You can also create an enrichment plugin to move this logic to a separate class so your track method is not overloaded.

https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#amplitude-sdk-plugin

**Comment by drewolbrich** [comment]
@izaaz Thank you. Here's the enrichment plugin I've created which performs the same function as the code above and doesn't require overloading the track method, as you suggested:
```
#if os(visionOS)

/// An Amplitude plugin that supplies the vendor system information that isn't
/// reported on visionOS in Amplitude-Swift 1.4.2.
private class MissingVendorSystemPlugin: Plugin {
    
    let type: PluginType

    var amplitude: Amplitude?

    init() {
        self.type = .enrichment
    }

    func setup(amplitude: Amplitude) {
        amplitude.configuration.trackingOptions.disableTrackDeviceManufacturer()
        amplitude.configuration.trackingOptions.disableTrackDeviceModel()
        amplitude.configuration.trackingOptions.disableTrackIDFV()
        amplitude.configuration.trackingOptions.disableTrackPlatform()
        amplitude.configuration.trackingOptions.disableTrackOsName()
        amplitude.configuration.trackingOptions.disableTrackOsVersion()

        self.amplitude = amplitude
    }

    func execute(event: BaseEvent) -> BaseEvent? {
        let eventOptions = EventOptions()

        eventOptions.deviceManufacturer = "Apple"
#if targetEnvironment(simulator)
        // This is consistent with the Amplitude-Swift SDK, which doesn't recognize the
        // simulator when running on an Apple Silicon Mac.
        eventOptions.deviceModel = ""
#else
        eventOptions.deviceModel = UIDevice.current.name
#endif
        eventOptions.idfa = UIDevice.current.identifierForVendor?.uuidString
        eventOptions.platform = UIDevice.current.systemName
        // This matches the behavior of the Amplitude-Swift SDK.
        eventOptions.osName = UIDevice.current.systemName.lowercased()
        eventOptions.osVersion = UIDevice.current.systemVersion

        event.mergeEventOptions(eventOptions: eventOptions)

        return event
    }

}

#endif // os(visionOS)
```

**Comment by drewolbrich** [comment]
> Thanks for the work around @drewolbrich. You can also create an enrichment plugin to move this logic to a separate class so your track method is not overloaded.
> 
> https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#amplitude-sdk-plugin

@izaaz FYI, the sample code at https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#enrichment-type-plugin is incorrect.

The `EnrichmentPlugin` class defines this method:
```
func execute(event: BaseEvent?) -> BaseEvent?
```
but the `Plugin` protocol in Amplitude-Swift 1.4.2 requires a method with this signature:
```
func execute(event: BaseEvent) -> BaseEvent?
```
Consequently, the `execute(event:)` method in the `EnrichmentPlugin` sample code will never be called by Mediator.swift in the SDK. The plugin won't have any effect, and no errors or warnings will be reported.

I wasted an hour tracking down why my enrichment plugin didn't work. At first, I assumed that the SDK had a bug, and enrichment plugins simply didn't work at all. 

Please fix the documentation so other developers who try to implement the sample code at https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#enrichment-type-plugin don't have the same issue. 

Thank you. 😊

**Comment by drewolbrich** [comment]
@sojingle I've tested `1.11.2` and the platform now appears to be reported correctly on visionOS. My plugin workaround is no longer necessary. Thank you! 😀
