### ISSUE TITLE
Broken Compilation using non-current SDKs

### ISSUE THREAD

**Issue by richardpiazza** [amplitude/Amplitude-Swift#140]
## Expected Behavior
The package should be able to compile correctly when using the non-current SDK (current is iOS 17, I have to use iOS 16.4 at the moment)

## Current Behavior
The package fails to compile due to the use of the `#available` macro added to the `HttpClient` in https://github.com/amplitude/Amplitude-Swift/pull/136.

```swift
if #available(macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0, *) {
    requestUrl = URL(string: url, encodingInvalidCharacters: false)
} else {
    requestUrl = URL(string: url)
}
```

The _available_ macro can behave unexpectedly when using version numbers that are not yet known from older SDK's. This leads to a build failure:

```
[22:29:14]: ▸ ::error file=/Users/runner/Library/Developer/Xcode/DerivedData/Patient-bmxfeexsbebtsienjupwzgepdxcj/SourcePackages/checkouts/Amplitude-Swift/Sources/Amplitude/Utilities/HttpClient.swift,line=74,col=70::extra argument 'encodingInvalidCharacters' in call
[22:29:14]: ▸             requestUrl = URL(string: url, encodingInvalidCharacters: false)
[22:29:14]: ▸        
```

## Possible Solution
Add an additional compiler check for a swift version to limit the available checking to a compatible version:

```swift
#if swift(>=5.9)
if #available(macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0, *) {
    requestUrl = URL(string: url, encodingInvalidCharacters: false)
} else {
    requestUrl = URL(string: url)
}
#else
// Fallback to the earlier behavior.
requestUrl = URL(string: url)
#endif
```

## Steps to Reproduce
I would suggest you setup your GitHub actions to run using a matrix of multiple versions of macOS/Xcode/SDKs to help in catching potential issues like this.

## Environment
- SDK Version: Since 1.4.0
- OS Info: macOS 14.3.1, Xcode 14.3.1, iOS 16.4

**Comment by crleona** [comment]
Thanks @richardpiazza, this is fixed in #141. It should be included in a release a bit later today.
