### ISSUE TITLE
Crash in SDK 

### ISSUE THREAD

**Issue by yqiang** [amplitude/Amplitude-Swift#145]
We are seeing crashes in our app in production from the Amplitude SDK. Unfortunately, there doesn't seem to be a consistent repro. In case it's helpful, we are calling the `identify` method from a `async` function.

Crash report:
<img width="971" alt="image" src="https://github.com/amplitude/Amplitude-Swift/assets/11876/ce4d9b5a-5e88-48e1-9d12-38a86b1af088">

## Environment
- SDK Version: 1.3.6
- OS Info: iOS 17.3.1

**Comment by crleona** [comment]
Hi @yqiang, can you please try to upgrade to Amplitude-Swift 1.4.0+? There have been some recent improvements that improved thread security in our storage classes.
