### ISSUE TITLE
EXC_BAD_ACCESS crash in PersistentStorage.swift

### ISSUE THREAD

**Issue by mt00chikin** [amplitude/Amplitude-Swift#158]
## Expected Behavior

PersistentStorage should not crash on a read

## Current Behavior

Since updating to Amplitude-Swift 1.4.2, we're seeing about 10 crashes/day in our application (>1MM active monthly users) coming from PersistentStorage's read function when the application returns to the foreground. This is low impact, but it's consistent.

## Possible Solution

I haven't had much time to investigate, but this might be related to the `sessions` lazy var on Amplitude.swift, which isn't being internally synchronized. There is already work being performed on the syncPersistentStorage.amplitude.com in the stack trace when the Session object is initialized.

## Steps to Reproduce
 

Currently unknown. The crash seems to be a race condition on foreground.

## Environment
- SDK Version:  1.4.2
- OS Info:  iOS 16 & iOS 17

Stack trace from the crash report:
[issue_91806d70e8647c1ba761c81369e030a5_crash_session_d384098f006940c4a55cd4ba8779485c_DNE_0_v2_stacktrace.txt](https://github.com/amplitude/Amplitude-Swift/files/15101383/issue_91806d70e8647c1ba761c81369e030a5_crash_session_d384098f006940c4a55cd4ba8779485c_DNE_0_v2_stacktrace.txt)

**Comment by crleona** [comment]
Hi @mt00chikin, The stack trace points to a crash calling `dispatch.sync` on one of our internal queues, which probably indicates a deadlock. Could you share more information about how you are calling ApplicationAnalyticsService.identifyIfNeeded (in terms of dispatch), as shown in the background thread in the stack trace?

**Comment by crleona** [comment]
Thanks @mt00chikin - I believe this is fixed by https://github.com/amplitude/Amplitude-Swift/pull/159 which should release later this week.

**Comment by crleona** [comment]
This should be fixed in 1.5.0.
