### ISSUE TITLE
Xcode reports hang risk from the Amplitude SDK

### ISSUE THREAD

**Issue by yqiang** [amplitude/Amplitude-Swift#160]
Xcode reports the following warning when running my app with the Amplitude SDK (version 1.4.5) installed:

Amplitude-Swift/Sources/Amplitude/Utilities/OutputFileStream.swift:40 {"message":"This code path does I/O on the main thread underneath that can lead to UI responsiveness issues. Consider ways to optimize this code path","antipattern trigger":"-[NSData enumerateByteRangesUsingBlock:]","message type":"suppressable","show in console":"0"}

<img width="368" alt="Screenshot 2024-05-09 at 9 26 52 AM" src="https://github.com/amplitude/Amplitude-Swift/assets/11876/a6f9be09-b78a-4c17-ab59-5b5f7b3091dc">

iOS 17.4.1
Xcode 15.3

**Comment by crleona** [comment]
Hi @yqiang, this should be fixed in 1.5.0 - please reopen this issue if it persists!
