### ISSUE TITLE
[Critical] Binary is rejected on AppStore Review

### ISSUE THREAD

**Issue by emartinson** [amplitude/Amplitude-Swift#162]
When I submit build to AppStore Review - after a while I get it rejected with: **Invalid Binary**

## Expected Behavior
Binary is not rejected.

## Current Behavior
`ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/AmplitudeSwift.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn‘t empty. Keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.`

## Possible Solution
I tried to set `Privacy Tracking Enabled` to YES in my own PrivacyManifest file. It seems to fix the preprocessing warning. But Binary is still gets rejected.

## Steps to Reproduce
1. Submit build to AppStore -> build is validated successfully
2. Add build to Version
3. Submit version to Review

## Environment
- SDK Version: 1.5.0
- OS Info: MacOS 13.5.2, XCode 15.2

<img width="999" alt="image" src="https://github.com/amplitude/Amplitude-Swift/assets/10173008/eb635fc6-f312-4a20-8e43-a564468a7020">
<img width="504" alt="image" src="https://github.com/amplitude/Amplitude-Swift/assets/10173008/3265460c-74dc-4f90-ac7c-8489f1e8bfa9">
<img width="346" alt="image" src="https://github.com/amplitude/Amplitude-Swift/assets/10173008/082a3f8a-61cf-4a55-8eb2-5b041ab21ca8">

**Comment by izaaz** [comment]
@emartinson are you using the latest version of the library? The domains were removed in version 1.4.5

https://github.com/amplitude/Amplitude-Swift/pull/155

**Comment by emartinson** [comment]
Yes, I do. I haven't figured out why I got these messages. I've managed to pass review by correcting local privacy manifest.
I think this issue may be closed
