### ISSUE TITLE
Is TrackingOptions.forCoppaControl supposed to be a static function?

### ISSUE THREAD

**Issue by danielmatzke** [amplitude/Amplitude-Swift#166]
The function `TrackingOptions.forCoppaControl` does not access the self object. It might be misleading since it looks like the function returns a COPPA-compliant version of the options it is being called on. I suggest either using the object the function is called on, or turning it into a static function.

https://github.com/amplitude/Amplitude-Swift/blob/f6efc4bda75c3c3092dc00d48c64b0096e076163/Sources/Amplitude/TrackingOptions.swift#L163-L170

**Comment by crleona** [comment]
Hi @danielmatzke, I agree this works better as a static function and is updated in #168, but please note this is not a public function and will be controlled through `Configuration.enableCoppaControl`
