### ISSUE TITLE
`ampli status` does not recognise functions as parameters

### ISSUE THREAD

**Issue by jvanderwee** [amplitude/Amplitude-Swift#173]
We'd like to use Ampli functions as function parameter e.g.
```
.onEnded(Ampli.instance.someEvent)
```
rather than in a trailing closure e.g.
```
.onEnded { Ampli.instance.someEvent() }
```

however this does not satisfy the `ampli status` checks.

## Expected Behavior

`ampli status` passes

## Current Behavior

`ampli status` fails

## Environment
Amplitude-Swift 1.5.0

**Comment by crleona** [comment]
Hi @jvanderwee, please open issues for Ampli on the https://github.com/amplitude/ampli-examples repo so they can be directed to the right place. Thanks!

**Comment by jvanderwee** [comment]
https://github.com/amplitude/ampli-examples/issues/326
