### ISSUE TITLE
Amplitude don't work with AppClip

### ISSUE THREAD

**Issue by Chargos** [amplitude/Amplitude-Swift#182]
## Expected Behavior
I want to see events from users who use my appClip with amplitude (https://developer.apple.com/app-clips/)

## Current Behavior
I receive error 400 error from server for session.uploadTask() in HttpClient.swift file:

      error
      value : Invalid id provided: omit the user_id or device_id field if they are unknown

      key : "code"
      value : 400

      key : "events_with_invalid_fields"
      key : device_id

Apple returns "00000000-0000-0000-0000-000000000000" for identifierForVendor for all AppClips
Functionality provided by [SKAdNetwork](https://developer.apple.com/documentation/storekit/skadnetwork) isn’t available for AppClips
Both [name](https://developer.apple.com/documentation/uikit/uidevice/1620015-name) and [identifierForVendor](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor) return an empty string for AppClips

## Possible Solution
Apple returns "00000000-0000-0000-0000-000000000000" for identifierForVendor for all AppClips, but amplitude can generate some temp id for appClips, then I could track Appclip users
(Generate some "id", save, then possibly merge events after the user installs the full version of the application, the saved identifier can be transmitted via App group shared user defaults)

## Steps to Reproduce
Just create AppClip, install amplitude into it and try send some event.

## Environment
- SDK Version:  1.6.1
- OS Info: iOS 16

**Comment by crleona** [comment]
This should be fixed with https://github.com/amplitude/Amplitude-Swift/pull/183, and released in 1.6.2.  Note that you'll have to either set a device id or reset the amplitude instance on affected devices.
