### ISSUE TITLE
Not receiving events

### ISSUE THREAD

**Issue by afern247** [amplitude/Amplitude-Swift#184]
## Summary

I have setup the SDK and I'm emitting events with:

```
private func trackEvent(eventType: String, properties: [String: Any]?) {
        guard let amplitude = amplitude else { return }
        
        let event = BaseEvent(
            eventType: eventType,
            eventProperties: properties
        )
        amplitude.track(event: event)
    }
```

but when I go to the website I don't see anything, is there a specific thing I need to look for on the website or add on my code?

**Comment by crleona** [comment]
@afern247 thank you for your feedback, I am glad you were able to get it working.
