### ISSUE TITLE
Provision for authorization headers in Amplitude SDK to route calls to third party url

### ISSUE THREAD

**Issue by KishanLal** [amplitude/Amplitude-Swift#216]
Currently Amplitude SDK support custom server url but I didn't find any provision to pass headers to route amplitude calls to this custom server url. Our organisation wants all amplitude requests to route to internal proxy server due to compliance reasons. I am able to achieve this with existing provision of custom server url but it fails due to missing authorization token. I can see this provision in JS SDK to pass custom headers but it is missing in iOS and Android SDK. Do we have any provision to pass custom headers to such third party requests. If not, any plan to add that support like JS SDK?

**Comment by crleona** [comment]
Hi @KishanLal, this is not currently supported. Please reach out to your account manager for support with any new feature requests.
