### ISSUE TITLE
Analytics issues with new SDK

### ISSUE THREAD

**Issue by Charchoghlyan** [amplitude/Amplitude-Swift#219]
I recently deleted the old Amplitude iOS SDK and installed the new version. Since then, I am receiving events correctly, but the analytics for metrics such as new users, daily active users (DAUs), and realtime users are not reflecting the correct data.

As shown in the attached screenshot, the chart's values drop to the bottom, indicating that the metrics for new users, DAUs, and realtime users have decreased to zero or are incorrectly displayed. This issue persists even though the events are being properly received.

<img width="1440" alt="Screenshot 2024-08-24 at 12 09 24 PM" src="https://github.com/user-attachments/assets/8e26ce0b-a945-46de-bfc5-b895066f6ab7">

**Comment by crleona** [comment]
Hi @Charchoghlyan, please double check that user and device Ids are being set consistently across both SDKs, and the event output from each SDK reflects these the same way. If there's a specific technical issue with the SDK we can help with, please let us know.

**Comment by crleona** [comment]
Hi @Charchoghlyan, I'm closing this due to lack of response, please feel free to reopen the issue if you can provide more details.
