### ISSUE TITLE
Migrating from Amplitude-iOS to Amplitude-Swift gives error in generated Ampli code

### ISSUE THREAD

**Issue by khurram18** [amplitude/Amplitude-Swift#223]
## Expected Behavior
The [Ampli](https://amplitude.com/docs/sdks/analytics/ios/ampli-for-ios-swift-sdk) should work without any errors when migrate from Amplitude-iOS to Amplitude-Swift.
- In generated Ampli.swift file it should contain`import AmplitudeSwift` instead of `import Amplitude`
- It should not refer any types that are not present in the new SDK.
- It should compile without any errors.
## Current Behavior
There are various compile time errors when using Ampli.
- No such model `Amplitude`
- Another compiler error is 
```
Cannot find AMPlan in scope
```
## Possible Solution
Please update Ampli to properly support Amplitude-Swift.

## Steps to Reproduce
Previously I am using Ampli with Amplitude-iOS and it works smoothly.
1. Remove Amplitude-iOS as dependency.
2. Add Amplitude-Swift as dependency.
3. Run `ampli pull`
4. Now compile the project and it will give the compile time errors.

## Environment
- SDK Version: Amplitude-Swift 1.9.0
- OS Info: 14.6.1

**Comment by crleona** [comment]
Hi @khurram18, in the future, please open Ampli related issues on the https://github.com/amplitude/ampli-examples repo. When updating SDKs, run `ampli configure` then `ampli pull` again. (if that does not work, you can delete ampli.json from your project's root then run `ampli init` again, which is equivalent to a full reset.)

**Comment by khurram18** [comment]
Thank you @crleona 
It worked by using `ampli config` and then `ampli pull` again.
