### ISSUE TITLE
How do I debug 400 errors?

### ISSUE THREAD

**Issue by DataGreed** [amplitude/Amplitude-Swift#227]
## Summary

Currently Amplitude  in my project returns 400 errors and the only way I know about this is because I have Sentry set up, but the Amplitude SDK does not print or provide any useful info about the errors. I tried setting `logLevel: .DEBUG` but it didn't change anything.

How do I get some meaningful debug info like http responses from Amplitude so I can handle them?

**Comment by crleona** [comment]
Hi @DataGreed - we're planning on improving logging in a future release, but I've improved some of the logging in http client so you can at least debug any issues you're seeing. Please try branch https://github.com/amplitude/Amplitude-Swift/tree/AMP-109939-improve-http-logging, or wait for a release in a few days.

**Comment by crleona** [comment]
This was released in 1.9.3
