### ISSUE TITLE
.NET MAUI support

### ISSUE THREAD

**Issue by MichaelLHerman** [amplitude/Amplitude-Swift#229]
## Summary

Any support for using Amplitude on .NET MAUI / Xamarin (Either iOS-only or cross platform)?

I see someone has created a project to create C# bindings  https://github.com/thisisthekap/Tonestro.Maui.Amplitude.iOS  but that appears to be for the deprecated https://github.com/amplitude/Amplitude-iOS SDK?

**Comment by crleona** [comment]
Hi @MichaelLHerman - unfortunately we do not have any support for .NET in our analytics SDKs.
