### ISSUE TITLE
Latitude & Longitude user properties not tracked on iOS

### ISSUE THREAD

**Issue by bastianfischer-neotaste** [amplitude/Amplitude-Swift#233]
My iOS events have no latitude/longitude assigned, while the Android ones have. Looking though the documentations I could find [this option for Android](https://amplitude.com/docs/sdks/analytics/android/android-kotlin-sdk#location-tracking), but none for iOS. Am I missing something or are the "Latitude" and "Longitude" user properties not available for iOS? The IP mapping (e.g. "City") works fine.

> By default, Amplitude can use Android location service (if available) to add the specific coordinates (longitude and latitude) for the location from which an event is logged. Control this behavior by enable / disable location listening during the initialization.

Thanks in advance!

**Comment by crleona** [comment]
Hi @bastianfischer-neotaste - Location is not tracked by default in Amplitude-Swift, we recommend creating a plugin to enrich events with location data. An example can be found in https://github.com/amplitude/Amplitude-Swift/blob/main/Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/LocationPlugin.swift

**Comment by bastianfischer-neotaste** [comment]
> Hi @bastianfischer-neotaste - Location is not tracked by default in Amplitude-Swift, we recommend creating a plugin to enrich events with location data. An example can be found in https://github.com/amplitude/Amplitude-Swift/blob/main/Examples/AmplitudeSwiftUIExample/AmplitudeSwiftUIExample/ExamplePlugins/LocationPlugin.swift

This helps a lot, thanks for clarifying! I'll try to apply this to our codebase.
