### ISSUE TITLE
How can I use Ampli CLI + autocapture for tracking lifecycle?

### ISSUE THREAD

**Issue by carlosmellado** [amplitude/Amplitude-Swift#245]
## Summary

I want to use the Ampli CLI for allowing product to manage all the event and properties, and it works nice, but I can't manage to make it work with lifecycle events as per documentation,  you recommend to use `autocapture`and it's not accessible or it's not working at all using the `Ampli.instance.load()` function.

The only way I make it work is doing something like this:

```
//Call to load()
Ampli.instance.load(LoadOptions(environment: .environment))
//Then change the defaultTracking Options
Ampli.instance.client.configuration.defaultTracking = DefaultTrackingOptions(sessions: true, appLifecycles: true, screenViews: true)
```

Even working, I see a warning because you deprecated `defaultTracking` in order to use `autocapture`.
But `autocapture` is a read-only property and can't be changed.

So, I would like to know your recommendations in order to use Ampli CLI and how to being able to change the autocapture options as well.

Thanks in advance.

**Comment by crleona** [comment]
Hi @carlosmellado, this appears to be an issue with Amplitude-Swift, not Amplitude-iOS, as we've only added autocapture in Amplitude-Swift.

To configure autocapture, please pass a configuration with the configured options to your ampli.load, something like `ampli.load(LoadOptions(client: LoadClientOptions(configuration: Configuration(apiKey: "", autocapture: [.sessions, .appLifecycles]))))`
