### ISSUE TITLE
Unable to install through Swift Package Manager

### ISSUE THREAD

**Issue by Vaisakhk1990** [amplitude/Amplitude-Swift#247]
Created a sample application and try to install the Amplitude SDK though SPM, Got Below error. We are following the instructions from this https://amplitude.com/docs/sdks/analytics/ios/ios-swift-sdk link 

<img width="1087" alt="Screenshot 2024-11-18 at 11 41 28 AM" src="https://github.com/user-attachments/assets/658bf13c-46d1-4b72-ac99-9313f09be366">

**Comment by crleona** [comment]
@Vaisakhk1990 please feel free to reopen if you are still having issues.

**Comment by roryprior** [comment]
I'm having a similar issue, resetting the package cache works temporarily but each time I switch branches on my project Xcode goes into an infinite loop of trying and failing to resolve the package. I've never seen this issue before with any other SPM and it's only occurred after migrating from the legacy Amplitude SDK. Could there be some kind of conflict between this SPM and the Amplitude Experiments or Session Replay SDKs? We use all three in our app.
