### ISSUE TITLE
reset() is not marked public

### ISSUE THREAD

**Issue by mooshee** [amplitude/Amplitude-Swift#31]
https://github.com/amplitude/Amplitude-Swift/blob/7f3449fc5b9c01c13049d79c3786361b33464e8d/Sources/Amplitude/Amplitude.swift#L254

I can't call `reset()` due to the function being marked as internal

**Comment by liuyang1520** [comment]
Thanks for supporting Amplitude! This issue should be fixed and released in v0.3.1.
