### ISSUE TITLE
Platform property contains device family

### ISSUE THREAD

**Issue by remvst** [amplitude/Amplitude-Swift#35]
## Expected Behavior

`platform` user property used to be `iOS` (on Android it is set to `Android`)

## Current Behavior
`platform` user property includes the device family i.e. `iPhone10,3`

## Steps to Reproduce
```swift
        override var platform: String {
            var name: [Int32] = [CTL_HW, HW_MACHINE]
            var size: Int = 2
            sysctl(&name, 2, nil, &size, nil, 0)
            var hw_machine = [CChar](repeating: 0, count: Int(size))
            sysctl(&name, 2, &hw_machine, &size, nil, 0)
            let platform = String(cString: hw_machine)

            return platform // expected: iOS, actual: iPhone10,3
        }
```

## Environment
- SDK Version: 0.3.0
- OS Info: iOS 15
- Equivalent Android SDK: 1.8.1

**Comment by gcgrant** [comment]
This also directly contradicts the documentation here
https://help.amplitude.com/hc/en-us/articles/215562387-User-property-definitions

and this community post 
https://community.amplitude.com/data-instrumentation-57/amplitude-what-values-will-appear-under-the-platform-user-property-483

**Comment by liuyang1520** [comment]
Thanks for supporting Amplitude! @yuhao900914 , do you have any suggestions on this?
