### ISSUE TITLE
Cannot Add Amplitude to Swift Package

### ISSUE THREAD

**Issue by seank90** [amplitude/Amplitude-Swift#36]
## Expected Behavior

We are trying to include Amplitude iOS as part of our package. 

## Current Behavior

It's not getting added when we compile the XCFramework file and is read as a missing dependency. 

## Steps to Reproduce
1. Create a SwiftUI Package and Add Amplitude
2. Try and compile the project into a XCFramework like so

```bash
xcodebuild archive \
 -scheme YOUR_PROJECT \
 -archivePath ./device/ \
 -sdk iphoneos \
 SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES DEFINES_MODULE=YES

xcodebuild archive \
 -scheme YOUR_PROJECT \
 -archivePath ./simulator/ \
 -sdk iphonesimulator \
 SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES DEFINES_MODULE=YES

xcodebuild -create-xcframework \
 -framework ./device.xcarchive/Products/Library/Frameworks/YOUR_PROJECT.framework \
 -framework ./simulator.xcarchive/Products/Library/Frameworks/YOUR_PROJECT.framework \
 -output ./YOUR_PROJECT.xcframework
```

4. Notice how the Amplitude framework is not included in the Archive or XCFramework

## Environment
- SDK Version: 0.3.0
- Device: All
- OS Version: iOS ~

**Comment by liuyang1520** [comment]
Thanks for supporting Amplitude!

@seank90 , could you elaborate how you "Add Amplitude"? We have these package managers supported: https://www.docs.developers.amplitude.com/data/sdks/sdk-quickstart/#install-the-dependency_4.

**Comment by seank90** [comment]
Hi @liuyang1520 

This is how we added it with Swift Package

```swift
let package = Package(
    name: "mobile-sdk-ios",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "mobile-sdk-ios",
            type: .dynamic,
            targets: ["mobile-sdk-ios"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/amplitude/Amplitude-Swift", from: "0.3.0"),
        .package(url: "https://github.com/getsentry/sentry-cocoa", from: "8.1.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "mobile-sdk-ios",
            dependencies: [
               "multiplatform-mobile",
                "Amplitude-Swift",
                .product(name: "Sentry", package: "sentry-cocoa")
            ],
            resources: [
                .copy("Resources/Lato-Regular.ttf"),
                .copy("Resources/Lato-Bold.ttf")
            ]
        ),
        .testTarget(
            name: "mobile-sdk-iosTests",
            dependencies: ["mobile-sdk-ios"]),
        .binaryTarget(name: "multiplatform-mobile",
                      path: "../multiplatform-mobile-sdk/build/swiftpackage/multiplatform-mobile.xcframework")
    ],
    swiftLanguageVersions: [.v5]
)

```

When we build and inspect the archive we get this as a result. 

![image](https://user-images.githubusercontent.com/9036207/219427163-9761f6ee-1c67-44c6-8cc7-ede3b9a906a5.png)

As you can see we don't have Amplitude included. Which is an issue.

**Comment by liuyang1520** [comment]
Thanks @seank90 !

I just search online about the XCFramework, here are some findings:
- It might be an issue related to https://forums.swift.org/t/issue-with-third-party-dependencies-inside-a-xcframework-through-spm/41977.
- There seems to be a wrapper solution with example: https://github.com/firebase/firebase-ios-sdk/blob/7.3.0/Package.swift#L211.

To follow up:
- I am not sure why in the package file you have `.product(name: "Sentry", package: "sentry-cocoa")`, is it possible to put `Amplitude-Swift` package there?
- Are you using the XCode Framework? If yes, is it possible to use [Swift Package](https://www.swift.org/package-manager/)?

**Comment by Mercy811** [comment]
Hi @seank90, would like to check in and see if this issue has been solved.

**Comment by Mercy811** [comment]
Closing this as it seems to be solved.
