### ISSUE TITLE
Events sent with “unknown” source

### ISSUE THREAD

**Issue by mattbischoff** [amplitude/Amplitude-Swift#39]
## Expected Behavior
Events should be reported in Amplitude as "ios" since I have set up a Source named "ios" in both my development and production environments. 

## Current Behavior
Events are reported as "unknown" when using the `Amplitude-Swift` SDK.

## Possible Solution
I think this might be happening because there’s no way to specify a `Plan` when [initializing the `Configuration`](https://github.com/amplitude/Amplitude-Swift/blob/main/Sources/Amplitude/Configuration.swift#L26). The reason for this is that `Plan` has no accessible public initializers.

## Steps to Reproduce
1. Create a Source in Amplitude’s web UI.
2. Setup the SDK with the API token for that source.
3. Track an event.

## Environment
- SDK Version: 0.3.1
- OS Info: iOS 16

**Comment by kelvinharron** [comment]
I've noticed this as well! It would be be a nice improvement to show it as ios, especially for non-technical users who may raise it as an issue when reviewing data.

**Comment by liuyang1520** [comment]
Thanks for supporting Amplitude!

Good call on the `Plan` initializer, I will add a public initializer for it in a coming PR. Just to confirm on the current behavior, for "unknown", do you mean the event on the Data (https://data.amplitude.com/) tracking plan?

**Comment by mattbischoff** [comment]
Yes!

**Comment by liuyang1520** [comment]
This should be fixed and released in [v0.3.2](https://github.com/amplitude/Amplitude-Swift/releases/tag/v0.3.2), please give it a try! Closing this now, thank you!
