### ISSUE TITLE
Out of session events

### ISSUE THREAD

**Issue by levochkaa** [amplitude/Amplitude-Swift#46]
## Expected Behavior
Session ID is correctly (not -1) set in all events, including the first session for this user.

## Current Behavior
Session ID is only correctly set in Start Session event for the first session of this user and all events in other sessions.

## Reason
Amplitude_Swift SDK doesn't get the sessionId for events in the first session, check this method:
```
@discardableResult
public func track(eventType: String, eventProperties: [String: Any]? = nil, options: EventOptions? = nil)
    -> Amplitude
```
## Possible solution
`track` method uses `LAST_EVENT_TIME` for `sessionId` on `BaseEvent` initialize

## Workaround
Using `sessionId`, when sending an event
```
amplitude.track(
	event: .init(
		sessionId: sessionId,
		eventType: eventType,
		eventProperties: eventProperties
	)
)
```
**Problems with this workaround:**
There is no documentation, so I've just used tried to use all these methods and none of them really helped me
![21 37 25 d9VhLlpB](https://user-images.githubusercontent.com/62802017/228932620-c4fd323b-387c-4273-8d07-e593a5ebb688.png)
but I stopped on using
```
let sessionId = Int64(Date().timeIntervalSince1970)
amplitude.refreshSessionTime(timestamp: sessionId)
UserDefaults.standard.set(sessionId, forKey: "sessionId")
```
When using this approach the sessionId in Start Session and other events don't match.
When trying to use other methods I get the same behavior or get End session in the first session of the user.

## Steps to Reproduce
 

1. Sample Amplitude configuration
```
let amplitude = Amplitude(configuration: Configuration(apiKey: amplitudeKey))
```
2. Use a new simulator/device, that hasn't been registered by Amplitude
3. Send any event
```
amplitude.track(eventType: eventType, eventProperties: eventProperties)
```
4. Check this user in Amplitude, It would have Start Session with Session ID, but other events would be **out-of-session** (Session ID == -1)
![21 31 25 xVCB5YbJ](https://user-images.githubusercontent.com/62802017/228931461-6e17d97c-0ba6-4670-b97f-697d48953a4f.png)

## Environment
- SDK Version: 0.3.0
- OS Info: iPadOS 14-16.4

**Comment by prokhorovxo** [comment]
I'm facing absolutely the same issue with `Amplitude-Swift` SDK.

**Comment by miloaton** [comment]
same here

**Comment by kennedyjosh** [comment]
#53 fixed some issues with session ids and events. Try updating to version 0.4.3
