### ISSUE TITLE
EventOptions

### ISSUE THREAD

**Issue by schwjustin** [amplitude/Amplitude-Swift#47]
'EventOptions' initializer is inaccessible due to 'internal' protection level

What is the correct way to add options to the track method? if EventOptions is inaccessible?

**Comment by schwjustin** [comment]
Any update on this?

**Comment by justin-fiedler** [comment]
Hi @schwjustin thanks for choosing Amplitude.

I just merged a fix but we have another change we want to include before the next release. Should have it released by EOW.

Thanks!

**Comment by justin-fiedler** [comment]
Released in `0.4.7`.
