### ISSUE TITLE
Disable IP Address tracking not working

### ISSUE THREAD

**Issue by luky88** [amplitude/Amplitude-Swift#55]
We have initialized the Amplitude Swift SDK using the tracking options, as described in the documentation, to disable some data tracking, including the user IP address.

However, even using the latest 0.4.4 SDK, the IP address is still collected and visible in the Amplitude dashboard.

Is there a way to completely and successfully disable it?

**Comment by Mercy811** [comment]
Hi @luky88, instead of creating a new workspace, you can also change both user id and device id to mimic a new user. Amplitude's backend use history IP address of users, so a new user should have no IP history.
