### ISSUE TITLE
Add the possibility to set the default disk location where to save SDK temporary files

### ISSUE THREAD

**Issue by luky88** [amplitude/Amplitude-Swift#56]
The Amplitude SDK creates an "amplitude" folder inside the app Documents directory and this is ok.

However, because our app needs to expose the Documents folder in the native iOS "Files" app, we would like to avoid exposing the "amplitude" folder too, but we there seems to be no way to change its location from the SDK.

Could it be possible to add such feature in the SDK config?

**Comment by Mercy811** [comment]
Hi @luky88, you can customize your own storage provider to persist events on [initialization](https://github.com/amplitude/Amplitude-Swift/blob/211d0c05830fab47e74fa9a053615cf422618a02/Sources/Amplitude/Configuration.swift#L42). Amplitude Swift SDK follows the same architecture in this [doc](https://www.docs.developers.amplitude.com/data/sdks/sdk-architecture/#storage-provider).
```
// Define YourOwnStorage() which implements Storage
// https://github.com/amplitude/Amplitude-Swift/blob/211d0c05830fab47e74fa9a053615cf422618a02/Sources/Amplitude/Types.swift#L62

Amplitude(
    configuration: Configuration(
        apiKey: "8c0fefcbd0effe2d799eb51be70053f8",
        storageProvider: YourOwnStorage()
        )
    )
```

We will add an example to the dev doc center soon❤️
