### ISSUE TITLE
Ampli Wrapper Not Yet Available

### ISSUE THREAD

**Issue by jvanderwee** [amplitude/Amplitude-Swift#66]
## Summary

When will the Ampli Wrapper be available for this SDK?

## Motivations

We would like to use Ampli codegen.

**Comment by justin-fiedler** [comment]
Hi @jvanderwee, thanks for choosing Amplitude.

We are in process adding Ampli support for the Swift SDK. We hope to have support complete by the end of August.

I will update this issue again once it is released.

Thanks again

**Comment by jvanderwee** [comment]
Hey @justin-fiedler ! are there any updates on this?

**Comment by justin-fiedler** [comment]
Hi @jvanderwee, we released Ampli for Swift SDK today. You will need CLI `v1.33.0+`. 

* Ampli for Swift SDK - https://www.docs.developers.amplitude.com/data/sdks/ios-swift/ampli
* Ampli migration from v1 -> v2 - https://www.docs.developers.amplitude.com/data/sdks/ios/ampli#migration

Let us know if you hit any issues. Thanks!
