### ISSUE TITLE
`flushEventsOnClose` configuration option fails to deliver events

### ISSUE THREAD

**Issue by tcldr** [amplitude/Amplitude-Swift#74]
## Expected Behavior
When the `flushEventsOnClose` configuration option is selected, any yet to be sent events will be flushed and delivered in a timely manner.

## Current Behavior
Whilst a call to `flush` is made, the network request will be immediately cancelled by the system as the app loses focus. Events won't be delivered until the user next opens the app at the earliest. If this is the last time a user opens an app, these critical events for diagnosing user attrition will fail to be delivered at all.

## Possible Solution
When an iOS app is backgrounded, any network requests which aren't specifically marked as background tasks will fail to complete. With the current implementation, this means that up to 30 seconds of events will be delayed until the next time the app is opened, or lost completely.

iOS does include an affordance to extend the time after an app loses foreground focus in which it can perform additional tasks, but these tasks need to be marked explicitly with calls to UIApplication.beginBackgroundTask and UIApplication.endBackgroundTask.

Unfortunately, this can't be achieved with an event callback alone as a background task should ideally be limited to around 5s, with a maximum deadline of 30s. This deadline is frequently exceeded with an event callback as the duration between when an event is tracked and when it is finally flushed through the queue frequently exceeds 30s and results in warnings from the system.

I've opened PR #68 as an example resolution, but would be happy with any solution or mechanism that ensures events can be successfully delivered.

## Environment
- SDK Version: v0.4.11
- OS Info: iOS 16/17

**Comment by justin-fiedler** [comment]
@tcldr fix is released in AmplitudeSwift `0.5.1`

**Comment by tcldr** [comment]
Great news – thanks you, all!
