### ISSUE TITLE
Add the build number to the user version property value

### ISSUE THREAD

**Issue by mdelbo** [amplitude/Amplitude-Swift#89]
## Summary

Currently it looks like the version property value is set to CFBundleShortVersionString from the info.plist file. This displays a version like `1.1` in amplitude's User Look-Up view. The complete version string should include the build number as well which is the CFBundleVersion value from the info.plist file. Incorporating the build number, the full version property would ideally look like this `1.1 (16)`

## Motivations

If the build number isn't incorporated in the version property value, it's not possible to tell exactly what version of the app a customer is using since the CFBundleShortVersionString is not incremented for every binary published.

**Comment by Mercy811** [comment]
Hi @mdelbo, we track CFBundleShortVersionString as version number by default. And in [default events](https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#tracking-default-events), we track CFBundleVersion as build number. See code [here](https://github.com/amplitude/Amplitude-Swift/blob/b05db31c2c19e1c6c3e47d168a83cc2f0e8cfb6e/Sources/Amplitude/Plugins/iOS/IOSLifecycleMonitor.swift#L71-L76).

If you want to let version number to be x.x (xx) format, you can use a enrichment plugin. Please refer to the [example](https://www.docs.developers.amplitude.com/data/sdks/ios-swift/#plugin-examples) and [docs](https://www.docs.developers.amplitude.com/data/sdk-plugins/).

**Comment by mdelbo** [comment]
Thanks, ok so to get the build number I need to set `defaultTracking.appLifecycles` to true since it's false by default. I can do that but it would be easier if it was recorded along with the user properties like version is.
