### ISSUE TITLE
CGFloat property values are not sent to backend

### ISSUE THREAD

**Issue by ryancrosby-bl** [amplitude/Amplitude-Swift#92]
## Expected Behavior
CGFloat property values should be sent to the backend, or raise an error.

## Current Behavior
The SDK silently fails to send these to the backend.

## Possible Solution
[Proposal PR](https://github.com/amplitude/Amplitude-Swift/pull/91)

## Steps to Reproduce
```
let properties = ["fontSize": CGFloat(12.0)]
amplitude.track(eventType: "userChangedFontSize", eventProperties: properties)
```

## Environment
- SDK Version: main / 0.7.2
- OS Info: iPadOS 17.0.3

**Comment by liuyang1520** [comment]
The change has been released in https://github.com/amplitude/Amplitude-Swift/releases/tag/v0.7.3.

Thanks again for reporting and contributing on this!
