### ISSUE TITLE
'Invalid JSON request body' error occurs when user minimizes app.

### ISSUE THREAD

**Issue by shynkevich-alex** [amplitude/Amplitude-Swift#99]
## Expected Behavior
Successful response (code 200)

## Current Behavior
{
	"code": 400,
	"error": "Invalid JSON request body"
}
![image](https://github.com/amplitude/Amplitude-Swift/assets/17390759/7d4b0bf3-183e-45f2-8f17-c429b84e6a86)

## Steps to Reproduce
 

1. Open iPhone settings
2. Open app
3. Change several permissions
4. Run
5. Minimze app (to trigger request)
6. Check request (use any sniffer like charles)

## Environment
- iPhone 13 mini, iOS 17.0.3
- AmplitudeSwift (1.0.0)

**Comment by Mercy811** [comment]
Hi @shynkevich-alex, it looks like you are using AmplitudeSwift 1.1.0 as it's the version client upload time added to. I ran the [example project ](https://github.com/amplitude/Amplitude-Swift/tree/main/Examples/AmplitudeSwiftUIExample)and it works well. Did you modify the payload yourself? To reproduce the error on our end, could you provide a minimum example? 
<img width="901" alt="image" src="https://github.com/amplitude/Amplitude-Swift/assets/31029607/d85d25bc-2c70-4175-8603-3dc67af276a3">

**Comment by shynkevich-alex** [comment]
Hi @Mercy811 , you are right I have 1.1.0 version.

I changed next permissions: Camera, Notifications, Photos, Location and Tracking.

But I noticed that I kill app from recents when change permissions and it looks like issue happens after it.
Try steps:
1. Run app
2. Kill app from recents
3. Run app again
4. minimize it after 2-5 seconds

**Comment by Mercy811** [comment]
Hi @shynkevich-alex, I still cannot reproduce it even by following your latest steps. Have you tried run the [example app](https://github.com/amplitude/Amplitude-Swift/tree/main/Examples/AmplitudeSwiftUIExample)?

**Comment by shynkevich-alex** [comment]
Hi @Mercy811 , I can't reproduce this issue on example app.
Will investigate what's wrong...
